#! /bin/bash

### BEGIN INIT INFO
# Provides:          IDENA
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IDENA service
# Description:       Run IDENA service
### END INIT INFO

# Statement configuration
case "$1" in
  start)
    echo "Starting IDENA..."
    #IDENA check
    screen -X -S $username quit
    screen -L -Logfile /home/$username/idena-go/idena_screen.log -S $username -dm /home/$username/idena-go/idena-go --config=/home/$username/idena-go/config.json --datadir=/home/$username/idena-go/datadir
    ;;
  stop)
    echo "Stopping IDENA..."
    screen -X -S $username quit
    sleep 2
    ;;
  restart)
    echo "Restarting IDENA..."
    screen -X -S $username quit
    cd /home/$username/idena-go/datadir/idenachain.db
    rm -rf ./* && wget -O main.zip https://github.com/ltraveler/idenachain.db/archive/refs/heads/main.zip && unzip -jo main.zip && rm main.zip  
    screen -L -Logfile /home/$username/idena-go/idena_screen.log -S $username -dm /home/$username/idena-go/idena-go --config=/home/$username/idena-go/config.json --datadir=/home/$username/idena-go/datadir
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/idena {start|stop}"
    exit 1
    ;;
esac

exit 0
